### ISSUE TITLE
Depends / Imports / LinkingTo

### ISSUE THREAD

**Issue by mpascariu** [MaciejDanko/gotm#1]
There are several packages specified in `Depends` in the `DESCRIPTION` file. This can create conflicts with other packages. My recommendation is to move  everything in `Imports` (if possible). Find a good explanation here: https://stackoverflow.com/questions/8637993/better-explanation-of-when-to-use-imports-depends

Additional notes received when I run `R CMD check` on my Windows machine:
```r
* checking package dependencies ... NOTE
Package in Depends/Imports which should probably only be in LinkingTo: 'RcppEigen'

* checking R code for possible problems ... NOTE
start.glm : <anonymous>: no visible binding for global variable
  'weights'
Undefined global functions or variables:
  weights
Consider adding
  importFrom("stats", "weights")
```

**Comment by MaciejDanko** [comment]
Thanks Marius!

The (fake) problem of "weights" was resolved by declaring variable weights explicitly in the start.glm() function. 

I also moved the packages: graphics, stats, and grDevices to Imports
