### ISSUE TITLE
better readme

### ISSUE THREAD

**Issue by soodoku** [MaciejDanko/gotm#10]
adding some of the core functions of the package in readme.md may prove useful along with some graphs etc. 

here are a couple of examples:
1. https://github.com/schuyler-smith/phylosmith/
2. https://github.com/peterjwatkins/diwanalr

not great but you get the idea. help people become aware of the API as quickly as possible.

**Comment by MaciejDanko** [comment]
I updated the readme file. Thank you.

**Comment by MaciejDanko** [comment]
I made some additional changes to the readme file. I hope the file is more informative now.
