### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by mpascariu** [MaciejDanko/gotm#2]
The use of special characters (e.g. German letters) can appear "funny" on computers that are using a UTF-8 encoding system (most English computers). For example in the `REFERENCES.bib` file there is `"Jürges, Hendrik"`; but when the package is installed in the help page will appear as `JÃƒÂ¼rges H`.

**Comment by MaciejDanko** [comment]
I'm using BibTex coding for special characters now (e.g. J\"{u}rges ).
I hope this resolved the issue.

**Comment by mpascariu** [comment]
Not really. I still see this `JÃ¼rges`.

**Comment by MaciejDanko** [comment]
Yes, thanks, I removed special characters from the bib file.
