### ISSUE TITLE
doi in .bib

### ISSUE THREAD

**Issue by soodoku** [MaciejDanko/gotm#6]
hey @MaciejDanko,

when you get a chance, add doi to the bib file: https://github.com/MaciejDanko/hopit/blob/master/paper/paper.bib

this is a requirement by JOSS.

Lumley -
https://www.jstatsoft.org/article/view/v009i08
DOI = 10.18637/jss.v009.i08

here's how to add doi to bibtex:
https://tex.stackexchange.com/questions/3802/how-to-get-doi-links-in-bibliography

**Comment by MaciejDanko** [comment]
missing DOIs were added
