### ISSUE TITLE
clearer contribution guidelines

### ISSUE THREAD

**Issue by soodoku** [MaciejDanko/gotm#7]
this is again a requirement for JOSS.

you can link to things like: 
https://www.tidyverse.org/articles/2017/08/contributing/

or write your own like:
https://github.com/justusschock/delira/blob/master/CONTRIBUTING.md

github also allows you to create a issue template
https://github.com/justusschock/delira/tree/master/.github/ISSUE_TEMPLATE

it doesn't need to be a large document but may be useful to clearly attend to JOSS criteria:
"Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

**Comment by MaciejDanko** [comment]
The detailed contribution guidelines were added
